"""Tests for Discord Markdown rendering in the rules editor.

``discord_markdown.py`` exists so the dashboard can preview the rules embed
with Discord's own (small, non-CommonMark) formatting rules, and warn about
syntax that renders literally. The security tests matter as much as the
formatting ones: rules text is written by one administrator and shown in
another administrator's browser, so every character of it must be escaped and
the only HTML in the output must be generated by the renderer.

Run with either:
    python -m pytest tests/test_markdown.py
    python tests/test_markdown.py
"""

from __future__ import annotations

import sys
import unittest
from html.parser import HTMLParser
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from discord_markdown import (  # noqa: E402
    EMBED_DESCRIPTION_LIMIT,
    lint_markdown,
    render_markdown_html,
)

# Tags the preview stylesheet knows about. Anything else in the output means
# the renderer leaked markup from the rules text.
ALLOWED_TAGS = {
    "a", "blockquote", "br", "code", "div", "em", "li", "ol", "pre", "s",
    "span", "strong", "u", "ul",
}


class _TagCollector(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=False)
        self.tags: list[str] = []
        self.attrs: list[tuple[str, str, str]] = []
        self.text: list[str] = []

    def handle_starttag(self, tag, attrs):
        self.tags.append(tag)
        self.attrs.extend((tag, name, value or "") for name, value in attrs)

    def handle_data(self, data):
        self.text.append(data)


def parse(rendered: str) -> _TagCollector:
    collector = _TagCollector()
    collector.feed(rendered)
    collector.close()
    return collector


class InlineFormattingTests(unittest.TestCase):
    def test_bold_italic_underline_strike_and_spoiler(self) -> None:
        html = render_markdown_html(
            "**bold** *italic* _italic_ __underline__ ~~strike~~ ||hidden||"
        )
        self.assertIn("<strong>bold</strong>", html)
        self.assertEqual(html.count("<em>italic</em>"), 2)
        self.assertIn("<u>underline</u>", html)
        self.assertIn("<s>strike</s>", html)
        self.assertIn('<span class="dm-spoiler"', html)
        self.assertIn(">hidden</span>", html)

    def test_formatting_is_not_applied_across_lines(self) -> None:
        # Discord ends bold/italic at the line break; the preview must too.
        html = render_markdown_html("**not\nbold**")
        self.assertNotIn("<strong>", html)
        self.assertIn("**not<br>bold**", html)

    def test_lone_asterisks_and_underscores_stay_literal(self) -> None:
        html = render_markdown_html("2 * 3 * 4 and snake_case_name")
        self.assertNotIn("<em>", html)
        self.assertIn("snake_case_name", html)

    def test_code_protects_formatting_characters(self) -> None:
        html = render_markdown_html("`**not bold**` and ```\n__not underlined__\n```")
        self.assertNotIn("<strong>", html)
        self.assertNotIn("<u>", html)
        self.assertIn('class="dm-code"', html)
        self.assertIn("<pre", html)


class BlockFormattingTests(unittest.TestCase):
    def test_headings_one_to_three_render_and_four_stay_literal(self) -> None:
        html = render_markdown_html("# One\n## Two\n### Three\n#### Four")
        self.assertIn('class="dm-h1">One<', html)
        self.assertIn('class="dm-h2">Two<', html)
        self.assertIn('class="dm-h3">Three<', html)
        # Discord shows four-or-more '#' as plain text.
        self.assertNotIn("dm-h4", html)
        self.assertIn("#### Four", html)

    def test_heading_without_a_space_is_a_paragraph(self) -> None:
        html = render_markdown_html("#NotAHeading")
        self.assertNotIn("dm-h1", html)
        self.assertIn("#NotAHeading", html)

    def test_blockquotes_group_and_multiline_quote_consumes_the_rest(self) -> None:
        html = render_markdown_html("> first\n> second\n\n>>> quoted\nstill quoted")
        self.assertEqual(html.count('<blockquote class="dm-quote">'), 2)
        self.assertIn("first<br>second", html)
        self.assertIn("quoted<br>still quoted", html)

    def test_bullet_and_numbered_lists(self) -> None:
        html = render_markdown_html("- one\n- two\n\n1. first\n2. second")
        self.assertIn('<ul class="dm-list"><li>one</li><li>two</li></ul>', html)
        self.assertIn('<ol class="dm-list"><li>first</li><li>second</li></ol>', html)

    def test_code_block_is_its_own_block(self) -> None:
        html = render_markdown_html("before\n```python\nx = 1\n```\nafter")
        self.assertIn('<pre class="dm-pre" data-lang="python"><code>x = 1\n</code></pre>', html)
        # The lines around it are separate paragraphs, not <br>-joined to code.
        self.assertNotIn("<br><pre", html)
        self.assertNotIn("</pre><br>", html)

    def test_subtext_and_paragraph_lines(self) -> None:
        html = render_markdown_html("line one\nline two\n-# small note")
        self.assertIn("line one<br>line two", html)
        self.assertIn('<div class="dm-subtext">small note</div>', html)

    def test_blank_input_renders_nothing(self) -> None:
        for value in ("", "   ", "\n\n", "\t"):
            with self.subTest(value=value):
                self.assertEqual(render_markdown_html(value), "")

    def test_control_characters_are_stripped(self) -> None:
        html = render_markdown_html("keep\x00this\x07clean")
        self.assertNotIn("\x00", html)
        self.assertNotIn("\x07", html)
        self.assertIn("keepthisclean", html)


class MentionAndLinkTests(unittest.TestCase):
    def test_mentions_render_as_pills(self) -> None:
        html = render_markdown_html("hi <@123> <@!456> <@&789> <#321> @everyone")
        self.assertEqual(html.count('class="dm-mention"'), 5)
        self.assertIn("&lt;@123>", html)

    def test_masked_link_and_autolink(self) -> None:
        html = render_markdown_html("[FAQ](https://example.com/faq) <https://example.com/a?b=1&c=2>")
        self.assertIn('href="https://example.com/faq"', html)
        # A query string must not be double-encoded.
        self.assertIn('href="https://example.com/a?b=1&amp;c=2"', html)
        self.assertNotIn("amp;amp", html)

    def test_non_http_links_are_not_made_clickable(self) -> None:
        html = render_markdown_html("[x](javascript:alert(1)) [y](ftp://example.com)")
        self.assertNotIn("<a ", html)
        self.assertIn("[x](javascript:alert(1))", html)


class SafetyTests(unittest.TestCase):
    """Rules text must never be able to inject markup into the dashboard."""

    def test_html_in_rules_text_is_escaped(self) -> None:
        html = render_markdown_html("<script>alert(1)</script> <img src=x onerror=alert(1)>")
        parsed = parse(html)
        self.assertNotIn("script", parsed.tags)
        self.assertNotIn("img", parsed.tags)
        # '<' is always escaped, so no tag can ever be formed.
        self.assertIn("&lt;script>alert(1)&lt;/script>", html)
        self.assertIn("&lt;img src=x onerror=alert(1)>", html)

    def test_only_renderer_generated_tags_are_emitted(self) -> None:
        hostile = (
            "<iframe src=//evil></iframe>\n"
            "<a href=\"javascript:alert(1)\">x</a>\n"
            "**b** <svg/onload=alert(1)> ||s|| `c` <@1> [l](https://ok.example)\n"
            "> quote\n- bullet\n# head\n```\n<div>raw</div>\n```"
        )
        parsed = parse(render_markdown_html(hostile))
        self.assertTrue(parsed.tags)
        self.assertLessEqual(set(parsed.tags), ALLOWED_TAGS, sorted(set(parsed.tags)))
        for tag, name, value in parsed.attrs:
            if name.startswith("on"):
                self.fail(f"event handler attribute leaked through: {tag} {name}")
            if name == "href":
                self.assertTrue(value.startswith("https://"), value)

    def test_attribute_values_cannot_break_out_of_the_anchor(self) -> None:
        html = render_markdown_html('<https://example.com/x>">')
        self.assertNotIn('">', html.split("</a>")[0].split(">", 1)[1][:0] or "")

    def test_placeholder_characters_from_the_user_are_harmless(self) -> None:
        # The renderer uses \x00 placeholders internally; a user cannot type
        # one, and a stray NUL must not disturb the output.
        html = render_markdown_html("text \x000\x00 **bold**")
        self.assertIn("<strong>bold</strong>", html)
        self.assertNotIn("\x00", html)


class LintTests(unittest.TestCase):
    def test_clean_markdown_produces_no_notes(self) -> None:
        clean = "# Rules\n**Be kind**\n- no spam\n> warned\n`code` <@1>"
        self.assertEqual(lint_markdown(clean), [])

    def test_unclosed_markers_are_reported(self) -> None:
        cases = {
            "**bold": "bold",
            "__under": "underline",
            "~~strike": "strikethrough",
            "||spoiler": "spoiler",
            "`code": "inline code",
        }
        for text, label in cases.items():
            with self.subTest(text=text):
                notes = lint_markdown(text)
                self.assertTrue(notes)
                self.assertIn(label, notes[0])

    def test_heading_notes(self) -> None:
        self.assertIn("#", lint_markdown("#### too deep")[0])
        # The heading can be any line, not just the first one.
        self.assertIn("#", lint_markdown("intro line\n#### too deep")[0])
        self.assertIn("space after", lint_markdown("#Rules")[0])
        self.assertIn("space after", lint_markdown("intro\n##Rules")[0])
        # A valid later heading must not be flagged by either note.
        self.assertEqual(lint_markdown("intro\n## Valid heading"), [])

    def test_mention_and_link_notes(self) -> None:
        self.assertIn("@everyone", lint_markdown("@everyone read this")[0])
        self.assertIn("http", lint_markdown("[docs](ftp://example.com)")[0])
        self.assertEqual(lint_markdown("[docs](https://example.com)"), [])

    def test_empty_text_has_no_notes(self) -> None:
        self.assertEqual(lint_markdown(""), [])
        self.assertEqual(lint_markdown("   \n "), [])


class LimitTests(unittest.TestCase):
    def test_embed_limit_matches_discords_description_limit(self) -> None:
        self.assertEqual(EMBED_DESCRIPTION_LIMIT, 4096)
        from rules import MAX_RULES_LENGTH

        self.assertEqual(EMBED_DESCRIPTION_LIMIT, MAX_RULES_LENGTH)


def main() -> int:
    suite = unittest.TestLoader().loadTestsFromModule(sys.modules[__name__])
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    raise SystemExit(main())
